/**
 * Vercel serverless entry: all requests are handled by the Express app.
 * Build must run first (npm run build) so ../dist/app.js exists.
 */
// @ts-ignore - dist is generated by build
import app from '../dist/app.js';
export default app;
