import { useEffect, useState } from 'react';
import { useTenant } from '../TenantContext';
import { api } from '../api';
import { useIsMobile } from '../hooks/useIsMobile';

type AgentNote = {
  noteId: string;
  tenantId: string;
  conversationId: string;
  userId: string | null;
  patientName: string | null;
  content: string;
  category: 'common_questions' | 'keywords' | 'analytics' | 'insights' | 'other';
  status: 'pending' | 'reviewed' | 'archived';
  createdAt: number | null;
  updatedAt: number | null;
  reviewedBy: string | null;
  reviewedAt: number | null;
};

export default function AgentNotes() {
  const { tenantId } = useTenant();
  const { isMobile } = useIsMobile();
  const [notes, setNotes] = useState<AgentNote[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filterStatus, setFilterStatus] = useState<'all' | 'pending' | 'reviewed' | 'archived'>('all');
  const [filterCategory, setFilterCategory] = useState<'all' | AgentNote['category']>('all');
  const [searchKeyword, setSearchKeyword] = useState('');
  const [consolidating, setConsolidating] = useState(false);
  const [showConsolidationDialog, setShowConsolidationDialog] = useState(false);
  const [consolidationResult, setConsolidationResult] = useState<{ notesConsolidated: number } | null>(null);

  const loadNotes = async () => {
    setLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams();
      if (filterStatus !== 'all') params.append('status', filterStatus);
      params.append('limit', '200');
      
      const url = `/tenants/${tenantId}/agent-notes${params.toString() ? `?${params.toString()}` : ''}`;
      const data = await api<{ notes: AgentNote[] }>(url);
      
      let filtered = data.notes;
      if (filterCategory !== 'all') {
        filtered = filtered.filter((n) => n.category === filterCategory);
      }
      if (searchKeyword.trim()) {
        const keyword = searchKeyword.trim().toLowerCase();
        filtered = filtered.filter((n) => 
          n.content.toLowerCase().includes(keyword) ||
          (n.patientName && n.patientName.toLowerCase().includes(keyword))
        );
      }
      
      setNotes(filtered);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to load notes');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadNotes();
  }, [tenantId, filterStatus, filterCategory, searchKeyword]);

  const updateNoteStatus = async (noteId: string, status: AgentNote['status']) => {
    try {
      await api(`/tenants/${tenantId}/agent-notes/${noteId}`, {
        method: 'PATCH',
        body: JSON.stringify({ status }),
      });
      await loadNotes();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to update note');
    }
  };

  const deleteNote = async (noteId: string) => {
    if (!confirm('Delete this note? This cannot be undone.')) return;
    try {
      await api(`/tenants/${tenantId}/agent-notes/${noteId}`, { method: 'DELETE' });
      await loadNotes();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to delete note');
    }
  };

  const runConsolidation = async () => {
    setConsolidating(true);
    setError(null);
    setConsolidationResult(null);
    try {
      const result = await api<{ notesConsolidated: number }>(`/tenants/${tenantId}/agent-notes/consolidate`, { method: 'POST' });
      await loadNotes();
      setConsolidationResult(result);
      setTimeout(() => {
        setConsolidationResult(null);
      }, 5000);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to run consolidation');
    } finally {
      setConsolidating(false);
      setShowConsolidationDialog(false);
    }
  };

  const categoryLabels: Record<AgentNote['category'], string> = {
    common_questions: 'Common Questions',
    keywords: 'Keywords',
    analytics: 'Analytics',
    insights: 'Insights',
    other: 'Other',
  };

  const categoryColors: Record<AgentNote['category'], string> = {
    common_questions: '#3b82f6',
    keywords: '#ef4444',
    analytics: '#10b981',
    insights: '#8b5cf6',
    other: '#64748b',
  };

  const statusColors: Record<AgentNote['status'], string> = {
    pending: '#f59e0b',
    reviewed: '#10b981',
    archived: '#94a3b8',
  };

  const pendingCount = notes.filter((n) => n.status === 'pending').length;

  return (
    <div>
      <h1 style={{ margin: '0 0 8px 0', fontSize: isMobile ? 24 : 32 }}>Agent Notes</h1>
      <p style={{ color: '#64748b', marginBottom: 32, maxWidth: 800 }}>
        Review automated insights and analytics generated by the agent during user conversations.
      </p>

      <div style={{ 
        display: 'flex', 
        justifyContent: 'space-between', 
        alignItems: 'center', 
        background: '#f8fafc', 
        padding: 20, 
        borderRadius: 12, 
        border: '1px solid #e2e8f0',
        marginBottom: 32,
        flexWrap: 'wrap',
        gap: 16
      }}>
        <div style={{ flex: '1 1 300px' }}>
          <h3 style={{ margin: '0 0 4px 0', fontSize: 16, color: '#0f172a' }}>Smart Consolidation</h3>
          <p style={{ fontSize: 13, color: '#64748b', margin: 0 }}>
            Merge similar notes and remove redundancies using AI.
          </p>
        </div>
        <button
          type="button"
          onClick={() => setShowConsolidationDialog(true)}
          disabled={consolidating || notes.length === 0}
          style={{
            padding: '10px 20px',
            fontSize: 14,
            fontWeight: 600,
            background: consolidating || notes.length === 0 ? '#94a3b8' : '#2563eb',
            color: '#fff',
            border: 'none',
            borderRadius: 8,
            cursor: consolidating || notes.length === 0 ? 'not-allowed' : 'pointer',
          }}
        >
          {consolidating ? 'Processing...' : 'Consolidate Notes'}
        </button>
      </div>

      {consolidationResult && consolidationResult.notesConsolidated > 0 && (
        <div style={{ padding: 12, background: '#f0fdf4', color: '#166534', borderRadius: 8, marginBottom: 24, fontSize: 14 }}>
          ✓ Successfully consolidated {consolidationResult.notesConsolidated} notes.
        </div>
      )}

      {error && (
        <div style={{ padding: 12, background: '#fef2f2', color: '#991b1b', borderRadius: 8, marginBottom: 24, fontSize: 14 }}>
          {error}
        </div>
      )}

      <div style={{ display: 'flex', gap: 12, marginBottom: 24, flexWrap: 'wrap' }}>
        <div style={{ flex: 1, minWidth: 200 }}>
          <input
            type="text"
            placeholder="Search notes..."
            value={searchKeyword}
            onChange={(e) => setSearchKeyword(e.target.value)}
            style={{ width: '100%' }}
          />
        </div>
        <select value={filterStatus} onChange={(e: any) => setFilterStatus(e.target.value)} style={{ minWidth: 140 }}>
          <option value="all">All Status</option>
          <option value="pending">Pending ({pendingCount})</option>
          <option value="reviewed">Reviewed</option>
          <option value="archived">Archived</option>
        </select>
        <select value={filterCategory} onChange={(e: any) => setFilterCategory(e.target.value)} style={{ minWidth: 160 }}>
          <option value="all">All Categories</option>
          <option value="common_questions">Common Questions</option>
          <option value="keywords">Keywords</option>
          <option value="analytics">Analytics</option>
          <option value="insights">Insights</option>
        </select>
      </div>

      {loading ? (
        <div style={{ color: '#64748b' }}>Loading notes...</div>
      ) : notes.length === 0 ? (
        <div style={{ padding: 48, textAlign: 'center', background: '#f8fafc', borderRadius: 12, border: '1px dashed #e2e8f0', color: '#94a3b8' }}>
          No notes found matching your criteria.
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          {notes.map((note) => (
            <div 
              key={note.noteId} 
              style={{ 
                padding: 20, 
                background: '#fff', 
                border: '1px solid #e2e8f0', 
                borderRadius: 12,
                boxShadow: '0 1px 2px rgba(0,0,0,0.05)'
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12, gap: 12 }}>
                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                  <span style={{ 
                    fontSize: 11, 
                    fontWeight: 700, 
                    textTransform: 'uppercase', 
                    padding: '2px 8px', 
                    borderRadius: 4, 
                    background: `${categoryColors[note.category]}15`, 
                    color: categoryColors[note.category] 
                  }}>
                    {categoryLabels[note.category]}
                  </span>
                  <span style={{ 
                    fontSize: 11, 
                    fontWeight: 700, 
                    textTransform: 'uppercase', 
                    padding: '2px 8px', 
                    borderRadius: 4, 
                    background: `${statusColors[note.status]}15`, 
                    color: statusColors[note.status] 
                  }}>
                    {note.status}
                  </span>
                </div>
                <div style={{ fontSize: 12, color: '#94a3b8' }}>
                  {note.createdAt ? new Date(note.createdAt).toLocaleDateString() : ''}
                </div>
              </div>
              
              <div style={{ fontSize: 15, color: '#1e293b', lineHeight: 1.6, whiteSpace: 'pre-wrap', marginBottom: 16 }}>
                {note.content}
              </div>
              
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid #f1f5f9', paddingTop: 12 }}>
                <div style={{ fontSize: 12, color: '#64748b' }}>
                  {note.patientName && <span>Patient: <strong>{note.patientName}</strong></span>}
                </div>
                <div style={{ display: 'flex', gap: 8 }}>
                  {note.status === 'pending' && (
                    <button 
                      onClick={() => updateNoteStatus(note.noteId, 'reviewed')}
                      style={{ padding: '6px 12px', fontSize: 12, fontWeight: 600, background: '#f0fdf4', color: '#166534', border: 'none', borderRadius: 6, cursor: 'pointer' }}
                    >
                      Mark Reviewed
                    </button>
                  )}
                  <button 
                    onClick={() => deleteNote(note.noteId)}
                    style={{ padding: '6px 12px', fontSize: 12, fontWeight: 600, background: 'transparent', color: '#ef4444', border: 'none', borderRadius: 6, cursor: 'pointer' }}
                  >
                    Delete
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {showConsolidationDialog && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(15, 23, 42, 0.3)', backdropFilter: 'blur(2px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 2000 }}>
          <div style={{ background: '#fff', borderRadius: 16, padding: 32, maxWidth: 480, width: '90%', boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)' }}>
            <h2 style={{ margin: '0 0 16px 0', fontSize: 20, color: '#0f172a' }}>Consolidate Notes</h2>
            <p style={{ margin: '0 0 24px 0', fontSize: 14, color: '#64748b', lineHeight: 1.6 }}>
              The agent will review all {notes.length} notes to identify and merge duplicates while preserving key information. This helps keep your insights clean and actionable.
            </p>
            <div style={{ display: 'flex', gap: 12, justifyContent: 'flex-end' }}>
              <button onClick={() => setShowConsolidationDialog(false)} style={{ padding: '10px 20px', fontSize: 14, background: '#fff', border: '1px solid #e2e8f0', borderRadius: 8, cursor: 'pointer', fontWeight: 500 }}>
                Cancel
              </button>
              <button onClick={runConsolidation} style={{ padding: '10px 24px', fontSize: 14, fontWeight: 600, background: '#2563eb', color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer' }}>
                Start Consolidation
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
